import {
  Task,
  TaskPriority,
  TaskStatus,
} from "../../features/task/models/task.model";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Complete Angular tutorial",
    description: "Learn about NgRx Signals",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.CRITICAL,
    createdAt: new Date(2025, 3, 25).toISOString(),
  },
  {
    id: "2",
    title: "Prepare project presentation",
    description: "Create slides for the team meeting",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 3, 25).toISOString(),
  },
  {
    id: "3",
    title: "Code review",
    description: "Review PRs for the backend team",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.LOW,
    createdAt: new Date(2025, 3, 26).toISOString(),
  },
  {
    id: "4",
    title: "Refactor authentication service",
    description: "Implement JWT token refresh mechanism",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    createdAt: new Date(2025, 3, 28).toISOString(),
  },
  {
    id: "5",
    title: "Fix responsive layout issues",
    description: "Address UI bugs on mobile devices",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 4, 2).toISOString(),
  },
  {
    id: "6",
    title: "Update dependencies",
    description: "Upgrade to latest Angular version",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.LOW,
    createdAt: new Date(2025, 4, 3).toISOString(),
  },
  {
    id: "7",
    title: "Implement dark mode",
    description: "Add theme switching functionality",
    status: TaskStatus.TODO,
    priority: TaskPriority.LOW,
    createdAt: new Date(2025, 4, 4).toISOString(),
  },
  {
    id: "8",
    title: "Write unit tests",
    description: "Increase test coverage for core modules",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    createdAt: new Date(2025, 4, 5).toISOString(),
  },
  {
    id: "9",
    title: "Optimize API calls",
    description: "Implement caching strategy",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 4, 6).toISOString(),
  },
  {
    id: "10",
    title: "Create user documentation",
    description: "Write guides for new features",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 4, 6).toISOString(),
  },
  {
    id: "11",
    title: "Setup CI/CD pipeline",
    description: "Configure GitHub Actions workflow",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.CRITICAL,
    createdAt: new Date(2025, 4, 7).toISOString(),
  },
  {
    id: "12",
    title: "Implement accessibility features",
    description: "Ensure WCAG 2.1 compliance",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    createdAt: new Date(2025, 4, 8).toISOString(),
  },
  {
    id: "13",
    title: "Performance audit",
    description: "Optimize initial load time",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.HIGH,
    createdAt: new Date(2025, 4, 8).toISOString(),
  },
  {
    id: "14",
    title: "Add internationalization",
    description: "Support multiple languages",
    status: TaskStatus.TODO,
    priority: TaskPriority.LOW,
    createdAt: new Date(2025, 4, 10).toISOString(),
  },
  {
    id: "15",
    title: "Security review",
    description: "Address vulnerabilities in authentication flow",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.CRITICAL,
    createdAt: new Date(2025, 4, 12).toISOString(),
  },
  {
    id: "16",
    title: "Conduct user interviews",
    description: "Collect feedback on new UI",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 4, 12).toISOString(),
  },
  {
    id: "17",
    title: "Bug bash",
    description: "Team-wide testing event",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.HIGH,
    createdAt: new Date(2025, 4, 14).toISOString(),
  },
  {
    id: "18",
    title: "Design sprint",
    description: "Prototype new onboarding flow",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 4, 14).toISOString(),
  },
  {
    id: "19",
    title: "Analytics setup",
    description: "Integrate GA4",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    createdAt: new Date(2025, 4, 16).toISOString(),
  },
  {
    id: "20",
    title: "QA Review",
    description: "Perform regression testing",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.LOW,
    createdAt: new Date(2025, 4, 17).toISOString(),
  },
  {
    id: "21",
    title: "Launch planning",
    description: "Coordinate with marketing",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 4, 18).toISOString(),
  },
  {
    id: "22",
    title: "Fix build issues",
    description: "Resolve CI pipeline errors",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.HIGH,
    createdAt: new Date(2025, 4, 18).toISOString(),
  },
  {
    id: "23",
    title: "Mobile UX testing",
    description: "Conduct usability testing on mobile",
    status: TaskStatus.TODO,
    priority: TaskPriority.CRITICAL,
    createdAt: new Date(2025, 4, 19).toISOString(),
  },
  {
    id: "24",
    title: "Cleanup unused code",
    description: "Improve maintainability",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.LOW,
    createdAt: new Date(2025, 4, 19).toISOString(),
  },
  {
    id: "25",
    title: "Onboard new team member",
    description: "Prepare access and documentation",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    createdAt: new Date(2025, 4, 20).toISOString(),
  },
];
